# fly.toml app configuration file generated for 1-hidden-resonance-8589 on 2025-04-16T14:29:43+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '1-hidden-resonance-8589'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
