# fly.toml app configuration file generated for fp-app-1-winter-tree-7552 on 2025-04-16T18:02:55+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fp-app-1-winter-tree-7552'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
